[tool.poetry]
name = "ai_tutor"
version = "0.1.0"
description = ""
authors = ["abhishek_arya abhishekarya436@gmail.com"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
